### PR TITLE
JBDS-4809: Integrate m2e-chromatic into Studio

### PR DESCRIPTION
**Pull request by sbouchet**
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

### CODE REVIEW

**Comment by sbouchet** [comment]
tested OK locally that the installer installs automatically the m2e-chromatic into the final product.

**Comment by jkopriva** [comment]
Works for me too. After installing newly build CRS plugin is present.

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Pull request merged**
