### PR TITLE
JBTIS-870 - add JBoss SOA Development to the installer update packs p…

### PR DESCRIPTION
**Pull request by pleacu**
…anel - Trivial change - add JBoss SOA Development to the install summary page.

install-soa2

@dgolovin @jeffmaury - please consider and push at your convenience

### CODE REVIEW

**Comment by pleacu** [comment]
@dgolovin @jeffmaury - Hey Denis/ Jeff - trivial 2 line change - can I get a push?  Thanks!

**Comment by jeffmaury** [comment]
@dgolovin relying on Denis as I though this would be done at the DevSuite installer level ?

**Comment by pleacu** [comment]
Hey Jeff - no this is a devstudio installer change (not devsuite).
              --paull

**Comment by dgolovin** [comment]
Released to master.

**Pull request merged**
