### PR TITLE
JBDS-3605 new graphics for installer header,...

### PR DESCRIPTION
**Pull request by nickboldt**
JBDS-3605 new graphics for installer header, about page, and splash; still need to update icon files in all billion places / sizes / formats

### CODE REVIEW

**Comment by maxandersen** [comment]
rejecting - JBDS-3605 is about 10.x, not 9.x.

**Comment by nickboldt** [comment]
These changes are for master branch, thus for 10.x. Reopening.

**Comment by maxandersen** [comment]
Please explain how a commit with images saying version 9 makes sense to have in master ?

**Comment by maxandersen** [comment]
doh - i misread the diff.

so why are we removing the version number ?

**Comment by nickboldt** [comment]
Because JBDS 10 shouldn't have a big 9 in it. And when we prototyped a version with a big "X" watermark instead of the 9 (because JBDS 10 = X) that looked meh too. Consensus from SJ and Alexey was to go w/o the watermark.

**Comment by maxandersen** [comment]
okey - would be good to have that documented in jira rather than just hipchat. anyway, these aren't the final forms so I still don't think this should go into our repos just yet.

**Pull request merged**
