### PR TITLE
JBIDE-26912: Remove Code Recommenders from the TP

### PR DESCRIPTION
**Pull request by sbouchet**
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

### CODE REVIEW

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Pull request merged**
