### PR TITLE
JBDS-4763: Rename installer devstudio binary files name to CodeReadyS…

### PR DESCRIPTION
**Pull request by jeffmaury**
…tudio

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@jeffmaury How about "crstudio" instead of "codereadystudio"? I would prefer shorter names, wdyt?

**Comment by jeffmaury** [comment]
@odockal CodeReady Workspace already used `codeready-xxx` so I'm would like to keep the installer to be `codeready-studio-xxx` but ok to rename scripts and launcher to `crstudio` but I'm wondering if it's not better to keep it for better coherence ? WDYT

**Comment by odockal** [comment]
@jeffmaury Oh ok, let's stick to others if they already use such naming convention, did not know that. Then it should be probably same everywhere to not to force people to remember or distinguish between two names in different situation but same product.

**Comment by odockal** [comment]
btw. the job is failing due to missing report files on given path (given by pattern) but there are no such tests. What tests are performed (what files are produced? there is no surefire plugin afaik) for product when `mvn clean verify` is called?

**Comment by jeffmaury** [comment]
There are some tests that are performed when the installer is build (by an ant script) but I don't think the output is JUnit compliant. So I think the PR job is wrongly configured as it always failed on this check

**Comment by odockal** [comment]
I has been a while.. since Feb 2018 :D I am fixing it now.

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@jeffmaury I am really not sure what test should be performed here. There is something happening at the end but who know. I removed the Junit publish results step and I also removed maven test error/failure ignore parameters from the maven execution, so if there are test, should fail now probably.

**Pull request merged**
