### PR TITLE
JBIDE-22696 use non-git-based timestamps for...

### PR DESCRIPTION
**Pull request by nickboldt**
JBIDE-22696 use non-git-based timestamps for update site and installer, including BUILD_ALIAS and BUILD_NUMBER ... are we sure we want this\?

### CODE REVIEW

**Comment by mickaelistria** [comment]
Is it necessary to keep the `hudson` profile?

**Comment by nickboldt** [comment]
Yes, if we want the B### suffix when built in Jenkins. Why not include it?

**Comment by mickaelistria** [comment]
Yeah, IIRC QE folks like to use the -B### suffix. @mlabuda Is this something useful for you?

**Comment by mlabuda** [comment]
Yes, this is useful. When something is wrong with build, it helps with hunting a bug. It is also useful for verification purpose to track specific build where issue has been verified.

**Pull request merged**
