### PR TITLE
JBDS-4417: Removing '-Dosgi.framework.extensions=org.eclipse.wst.jsdt…

### PR DESCRIPTION
**Pull request by ibuziuk**
….nashorn.extension' from eclipse.ini.devstudio

Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### CODE REVIEW

**Comment by ibuziuk** [comment]
cc: @nickboldt @vrubezhny

**Comment by jeffmaury** [comment]
I thought it was request by the JS tooling ?. @nickboldt has a different proposal

**Comment by ibuziuk** [comment]
@jeffmaury there is a discussion in https://issues.jboss.org/browse/JBDS-4417
For Oxygen there is no need for Nashorn since Closure compiler is used instead

**Comment by nickboldt** [comment]
This PR misses fixing the product definition. See #457 for more complete PR. Note too that I don't think the eclipse.ini file in the rpm/ folder is actually USED. This fix, to remove nashorn extension, is probably going to have to be done in upstream rh-eclipse47 rpm. cc: @mbooth101

**Pull request closed without merging**
