### PR TITLE
JBDS-2044 switch from o.e.platform feature to plugin

### PR DESCRIPTION
**Pull request by nickboldt**
switch from o.e.platform feature to plugin

### CODE REVIEW

**Comment by mickaelistria** [comment]
Why?

**Comment by nickboldt** [comment]
See JBDS-2044

**Comment by mickaelistria** [comment]
Ok, thanks. That seems like a good patch. However, removing this feature seems dangerous as IIRC it includes some bundles that are necessary for the e4 framework but not required by other bundle (org.eclipse.e4.di or similar IIRC). Do you have a p2diff of what's in and out for JBDS repo and product with that change?

**Comment by nickboldt** [comment]
Turns out this patch does nothing because devstudio includes a number of features which depend explicitly on org.eclipse.platform feature, not just the org.eclipse.platform plugin:

o.e.m2e.wtp.feature
o.e.m2e.jaxrs.feature
o.e.m2e.jpa.feature
o.e.m2e.jsf.feature
o.j.t.maven.cdi.feature
o.j.t.maven.feature
o.j.t.maven.hibernatefeature
o.j.t.maven.project.examples.feature
o.j.t.maven.sourcelookup.feature
o.sonatype.m2e.egit.feature

**Comment by mickaelistria** [comment]
So it doesn't change any content, but fixes JBDS-2044? Then +1

**Comment by nickboldt** [comment]
Well, actually, it doesn't appear to change anything. The .eclipseproduct file still contains information about Eclipse, not devstudio. But this is most likely because the platform.feature is still being installed, as it's being dragged in by all the other features above, which depend on it.

**Pull request closed without merging**
